# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{demeter}
  s.version = "1.0.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Emerson Macedo"]
  s.date = %q{2010-01-05}
  s.description = %q{A simple way to apply the Law of Demeter to your Ruby objects.}
  s.email = %q{emerleite@gmail.com}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "README.markdown",
     "Rakefile",
     "VERSION",
     "demeter.gemspec",
     "lib/demeter.rb",
     "lib/demeter/active_record.rb",
     "lib/demeter/version.rb",
     "spec/demeter/active_record_spec.rb",
     "spec/demeter/demeter_spec.rb",
     "spec/resources/classes.rb",
     "spec/resources/models.rb",
     "spec/schema.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/emerleite/demeter}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A simple way to apply the Law of Demeter to your Ruby objects.}
  s.test_files = [
    "spec/demeter/active_record_spec.rb",
     "spec/demeter/demeter_spec.rb",
     "spec/resources/classes.rb",
     "spec/resources/models.rb",
     "spec/schema.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

